- name: Configure nginx web root folder to serve web page from our custom folder in Ubuntu ansible node
  when: ( ansible_distribution == "Ubuntu" and ansible_os_family == "Debian" )
  copy: src=default dest=/etc/nginx/sites-available/default
