- name: Configure nginx web root folder to serve web page from our custom folder in Ubuntu ansible node
  when: ( ansible_distribution == "Rocky" and ansible_os_family == "RedHat" )
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
