- name: Install Extra Packages for Enterprise Linux(epel-release) in Rocky ansible node
  when: ( ansible_distribution == "Rocky" and ansible_os_family == "RedHat" )
  yum: name=epel-release state=latest

- name: Install nginx web server in Rocky ansible node
  when: ( ansible_distribution == "Rocky" and ansible_os_family == "RedHat" )
  yum: name=nginx state=latest
