- name: This playbook will install nginx web server, configures its web root folder and deploys a custom web page
  hosts: all
  vars_files:
  - nginx-vars.yml
  tasks:
  - include: install-nginx-ubuntu.yml
  - include: install-nginx-rocky.yml

  - include: start-nginx-ubuntu.yml
  - include: start-nginx-rocky.yml

  - include: configure-nginx-ubuntu.yml
  - include: configure-nginx-rocky.yml

  - include: restart-nginx-ubuntu.yml
  - include: restart-nginx-rocky.yml

  - include: common-nginx-tasks.yml
