- name: This playbook will install nginx web server, configures its web root folder and deploys a custom web page
  hosts: all
  vars_files:
  - nginx-vars.yml
  tasks:
  - include: install-nginx-ubuntu.yml
  - include: install-nginx-rocky.yml

  - include: start-nginx-ubuntu.yml
  - include: start-nginx-rocky.yml

  - name: Create the custom web root folder
    file: path=/var/html state=directory mode=0755

  - include: configure-nginx-ubuntu.yml
  - include: configure-nginx-rocky.yml

  - include: restart-nginx-ubuntu.yml
  - include: restart-nginx-rocky.yml

  - name: Retrieve IP address
    shell: hostname -i
    register: ip_address

  - debug: var=ip_address

  - name: Deploy custom web page
    #copy: src=index.html dest=/var/html/index.html
    template: src=index.html.j2 dest=/var/html/index.html
