- name: This playbook will install nginx web server, configures its web root folder and deploys a custom web page
  hosts: all
  vars_files:
  - nginx-vars.yml
  tasks:
  - include_tasks: install-nginx-ubuntu.yml
  - include_tasks: install-nginx-rocky.yml

  - include_tasks: start-nginx-ubuntu.yml
  - include_tasks: start-nginx-rocky.yml

  - include_tasks: configure-nginx-ubuntu.yml
  - include_tasks: configure-nginx-rocky.yml

  - include_tasks: restart-nginx-ubuntu.yml
  - include_tasks: restart-nginx-rocky.yml

  - include_tasks: common-nginx-tasks.yml
