- name: Create the custom web root folder
  file: path=/var/html state=directory mode=0755

- name: Retrieve IP address
  shell: hostname -i
  register: ip_address

- debug: var=ip_address

- name: Deploy custom web page
  template: src=index.html.j2 dest=/var/html/index.html
